name: Package Rspamd for Debian Sid

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup GPG
        # The cursed private key is too big for a Github Secret.
        # Getting around that by keeping it encrypted within the repo.
        run: |
          export GPG_TTY=$(tty)
          gpg --batch --decrypt --passphrase='${{ secrets.GPG_PASSPHRASE }}' --output debian/SIGNING-KEY  debian/SIGNING-KEY.gpg
          gpg --batch --pinentry-mode loopback --import debian/SIGNING-KEY
          #rm -f debian/SIGNING-KEY*
          echo F21F35DB39C2C7D93C9B534C43AD361BAF83FB7D:6: | gpg --import-ownertrust
          gpg -K
      - name: Changelog and Version Fix
        run: |
          sed -i 's/quilt/native/' debian/source/format
          VERS=$(head -1 ChangeLog | cut -f1 -d:)
          echo "rspamd ($VERS) unstable; urgency=low" > debian/changelog
          echo >> debian/changelog
          tail -n +2 ChangeLog | sed -e '/^$/,$d' >> debian/changelog
          echo >> debian/changelog
          echo " -- Christopher Funderburg <chris@funderburg.me>  $(date -R)" >> debian/changelog
          cat debian/changelog
      - name: Build
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=full --force-sign
          docker-image: debian:sid
          extra-build-deps: apt-utils devscripts
          setup-hook: |
            apt update
            apt install gpg -y
            export GPG_TTY=$(tty)
            export GNUPGHOME=`pwd`
            gpg --batch --decrypt --passphrase='${{ secrets.GPG_PASSPHRASE }}' --output debian/SIGNING-KEY  debian/SIGNING-KEY.gpg
            gpg --batch --pinentry-mode loopback --import debian/SIGNING-KEY
            rm -f debian/SIGNING-KEY*
            echo F21F35DB39C2C7D93C9B534C43AD361BAF83FB7D:6: | gpg --import-ownertrust
            gpg -K
      - name: Manual Signing
        run: |
          
      - uses: actions/upload-artifact@v4
        with:
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: debian/artifacts/*
